<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXkxrqem\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXkxrqem/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXkxrqem.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXkxrqem\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXkxrqem\appProdProjectContainer([
    'container.build_hash' => 'Xkxrqem',
    'container.build_id' => 'ff9139e3',
    'container.build_time' => 1582196445,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXkxrqem');
